<MyGrid>
  # variable on right side is the id in .kv
  # variable on left side is the ObjectProperty in .py
  name: name
  email: email

  GridLayout:
    cols:1
    size: root.width, root.height

    GridLayout: 
      cols: 2

      Label:
        text: "Name: "

      TextInput:
        id: name
        multiline: False

      Label:
        text: "Email: "

      TextInput:
        id: email
        multiline: False
    
    Button:
      text: "Submit"
      on_press: root.btn()